### ISSUE TITLE
求助 “图片执行状态 未知错误”

### ISSUE THREAD

**Issue by AngelBamboo** [yuban10703/OPQ-SetuBot#11]
不知道怎么办好了 求助dalao

**Comment by yuban10703** [comment]
windows不能发图，换Linux

**Comment by AngelBamboo** [comment]
谢谢dalao 我去装个虚拟机试一下

**Comment by AngelBamboo** [comment]
![QQ截图20200812033215](https://user-images.githubusercontent.com/69456059/89935094-9134c000-dc4c-11ea-878e-15c6305ae18f.png)
dalao 我在Ubuntu18的服务器上无法运行sex_pic.py 这是为什么
