### ISSUE TITLE
图片消息执行状态:[Ret:('未知错误:', TypeError("'NoneType' object is not subscriptable",))]

### ISSUE THREAD

**Issue by qq985382384** [yuban10703/OPQ-SetuBot#14]

**Comment by qq985382384** [comment]
![ARMJ5FLVY9BJARI_U1K{G(3](https://user-images.githubusercontent.com/53076564/92384282-656d0300-f142-11ea-9325-3b2da1ab0d76.png)

**Comment by yuban10703** [comment]
啊?....

**Comment by qq985382384** [comment]
> 啊?....

连接成功
文字消息执行状态:[Ret:0]
从yubanのapi获取到1张setu
图片消息执行状态:[Ret:('未知错误:', TypeError("'NoneType' object is not subscriptable",))]
从yubanのapi获取到1张setu
图片消息执行状态:[Ret:('未知错误:', TypeError("'NoneType' object is not subscriptable",))]
文字消息执行状态:[Ret:0]

ubuntu也不能发送图片类型吗

**Comment by yuban10703** [comment]
你手动用浏览器插件发一下图片试试?....
应该没问题鸭...
