### ISSUE TITLE
ascii语法错误？？？

### ISSUE THREAD

**Issue by WannaCry705** [yuban10703/OPQ-SetuBot#15]
![Screenshot_20200920_152811](https://user-images.githubusercontent.com/71083083/93706531-b43d7400-fb16-11ea-814a-492ee37a17d7.jpg)
请问这个是什么情况

**Comment by yuban10703** [comment]
肯定不行啊.....

**Comment by yuban10703** [comment]
python3版本?....

**Comment by WannaCry705** [comment]
嗯

**Comment by yuban10703** [comment]
换3.8试试

**Comment by WannaCry705** [comment]
👌我周末去试试,thanks a lot

**Comment by WannaCry705** [comment]
ok可以运行了，
现在在做iotbot那个项目
有问题会issue的，
再次感谢
