### ISSUE TITLE
私聊原图不起作用

### ISSUE THREAD

**Issue by MapleNe** [yuban10703/OPQ-SetuBot#17]
私聊原图为true之后不起作用，还是缩略图

**Comment by yuban10703** [comment]
确定是私聊(群聊临时会话)么,不是好友会话么?
![K `4SRLRX91$CM%$PJH1@VX](https://user-images.githubusercontent.com/39484884/98902849-6bd87c00-24f1-11eb-8b0b-fac6c0fb9cb6.jpg)

**Comment by MapleNe** [comment]
> 确定是私聊(群聊临时会话)么,不是好友会话么?
> ![K `4SRLRX91$CM%$PJH1@VX](https://user-images.githubusercontent.com/39484884/98902849-6bd87c00-24f1-11eb-8b0b-fac6c0fb9cb6.jpg)

啊这，确实是好友会话
