### ISSUE TITLE
启动时出现错误

### ISSUE THREAD

**Issue by TeoZler** [yuban10703/OPQ-SetuBot#18]
在输入` python3 bot_setu_v3.py `后返回：
`
  File "bot_setu_v3.py", line 224
    if data := db_tmp.table('sentlist').search(
                ^
SyntaxError: invalid syntax
`
![Snipaste_2020-11-23_23-49-31](https://user-images.githubusercontent.com/43093562/99983384-bfe33a80-2de6-11eb-97f3-56b115951977.png)

**Comment by yuban10703** [comment]
py版本是多少?

**Comment by TeoZler** [comment]
我的锅，查了一下是版本问题。
但是输入 `python3.8 bot_setu_v3.py `时
会返回
```
Traceback (most recent call last):
  File "bot_setu_v3.py", line 1, in <module>
    from iotbot import IOTBOT, Action, FriendMsg, GroupMsg, EventMsg
ModuleNotFoundError: No module named 'iotbot'
```
![2](https://user-images.githubusercontent.com/43093562/99983827-54e63380-2de7-11eb-9878-1ab0ceb4c0e9.png)

**Comment by yuban10703** [comment]
没装模块

**Comment by yuban10703** [comment]
python3.8 -v pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by TeoZler** [comment]
输入`python3.8 -v pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple`后
会显示`python3.8: can't open file 'pip': [Errno 2] No such file or directory`
查询pip版本后查到的是py3.6的pip

**Comment by yuban10703** [comment]
你自己查一下怎么改pip默认的python版本吧......

**Comment by yuban10703** [comment]
https://www.cnblogs.com/52forjie/p/10107160.html
