### ISSUE TITLE
关于获取pixiv的token错误

### ISSUE THREAD

**Issue by CheapMan233** [yuban10703/OPQ-SetuBot#19]
![image](https://user-images.githubusercontent.com/43162693/101274040-af41a580-3792-11eb-998b-bd7851fe6046.png)
请问这是怎么回事

**Comment by yuban10703** [comment]
科学上网了么?..

**Comment by CheapMan233** [comment]
是的挂了ssr的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yuban10703"<notifications@github.com&gt;; 
发送时间: 2020年12月6日(星期天) 下午5:18
收件人: "yuban10703/OPQ-SetuBot"<OPQ-SetuBot@noreply.github.com&gt;; 
抄送: "Taojian Zhou"<1207323843@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yuban10703/OPQ-SetuBot] 关于获取pixiv的token错误 (#19)





 
科学上网了么?..

**Comment by CheapMan233** [comment]
顺便再问一下，怎么关闭群主和管理员对机器人的默认权限啊

**Comment by yuban10703** [comment]
阿哲，关不了。。。

**Comment by CheapMan233** [comment]
ok，thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yuban10703"<notifications@github.com&gt;; 
发送时间: 2020年12月7日(星期一) 下午3:31
收件人: "yuban10703/OPQ-SetuBot"<OPQ-SetuBot@noreply.github.com&gt;; 
抄送: "Taojian Zhou"<1207323843@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yuban10703/OPQ-SetuBot] 关于获取pixiv的token错误 (#19)





 
阿哲，关不了。。。
