### ISSUE TITLE
更新6.0.3之后发色图裂图

### ISSUE THREAD

**Issue by HeiLAAS** [yuban10703/OPQ-SetuBot#20]
如题..

**Comment by yuban10703** [comment]
啊?不是才6.0.2么...

**Comment by yuban10703** [comment]
log返回正常么?
正常的话可能是tx的问题,挂几天就好了

**Comment by HeiLAAS** [comment]
好像是api 0的地址炸了…

**Comment by MapleNe** [comment]
> log返回正常么?
> 正常的话可能是tx的问题,挂几天就好了

api0修一修吧

**Comment by CheapMan233** [comment]
确实，其他功能正常可以发图，只有setu发不出来很奇怪

**Comment by yuban10703** [comment]
有空修

**Comment by HeiLAAS** [comment]
> 确实，其他功能正常可以发图，只有setu发不出来很奇怪

你的色图插件可以正常运行吗？我运行一会就自动退出了

**Comment by yuban10703** [comment]
az,在重写了.........50%
