### ISSUE TITLE
socket总自动断开,断开两次后就自动停止运行

### ISSUE THREAD

**Issue by DoneBootbloader** [yuban10703/OPQ-SetuBot#21]
#sample
![Screenshot 2020-12-18 110302](https://user-images.githubusercontent.com/46632557/102569736-f891dd80-4120-11eb-9e70-e2294400016b.png)

**Comment by wangzhe1220** [comment]
我也出现了这个问题，因为刚用python没多久，还没找到解决的办法
我用另一种方式解决了这个问题：
新建autorun.sh，并修改文件权限使其可以被执行，这个脚本的作用是只要检测程序挂掉，立刻重新运行：
#!/bin/sh 
while true
do
count=`ps -ef |grep bot_setu |grep -v "grep" |wc -l`
echo $count
if [ 0 == $count ];
then
python /usr/local/OPQ-SetuBot-master/bot_setu_v3.py 
echo "setubot has been restarted!"
else
echo "setubot already started!"
fi
sleep 10
done

python /usr/local/OPQ-SetuBot-master/bot_setu_v3.py 这条命令可以替换为你的相应命令
使用screen命令后台执行autorun.sh

**Comment by yuban10703** [comment]
阿哲....等我重写吧......

**Comment by DoneBootbloader** [comment]
> 我也出现了这个问题，因为刚用python没多久，还没找到解决的办法
> 我用另一种方式解决了这个问题：
> 新建autorun.sh，并修改文件权限使其可以被执行，这个脚本的作用是只要检测程序挂掉，立刻重新运行：
> #!/bin/sh
> while true
> do
> count=`ps -ef |grep bot_setu |grep -v "grep" |wc -l`
> echo $count
> if [ 0 == $count ];
> then
> python /usr/local/OPQ-SetuBot-master/bot_setu_v3.py
> echo "setubot has been restarted!"
> else
> echo "setubot already started!"
> fi
> sleep 10
> done
> 
> python /usr/local/OPQ-SetuBot-master/bot_setu_v3.py 这条命令可以替换为你的相应命令
> 使用screen命令后台执行autorun.sh

啊这，直接用pm2进程守护不好吗
pm2 start bot_setu_v3.py -x --interpreter python3

**Comment by wangzhe1220** [comment]
> > 我也出现了这个问题，因为刚用python没多久，还没找到解决的办法
> > 我用另一种方式解决了这个问题：
> > 新建autorun.sh，并修改文件权限使其可以被执行，这个脚本的作用是只要检测程序挂掉，立刻重新运行：
> > #!/bin/sh
> > while true
> > do
> > count=`ps -ef |grep bot_setu |grep -v "grep" |wc -l`
> > echo $count
> > if [ 0 == $count ];
> > then
> > python /usr/local/OPQ-SetuBot-master/bot_setu_v3.py
> > echo "setubot has been restarted!"
> > else
> > echo "setubot already started!"
> > fi
> > sleep 10
> > done
> > python /usr/local/OPQ-SetuBot-master/bot_setu_v3.py 这条命令可以替换为你的相应命令
> > 使用screen命令后台执行autorun.sh
> 
> 啊这，直接用pm2进程守护不好吗
> pm2 start bot_setu_v3.py -x --interpreter python3

学到新姿势了= =

**Comment by HeiLAAS** [comment]
这个是python-iot模块的问题。2.7.0就莫得问题
pip3 install python-iotbot==2.7.0

**Comment by DoneBootbloader** [comment]
> 这个是python-iot模块的问题。2.7.0就莫得问题
> pip3 install python-iotbot==2.7.0

嗯,换上了270,现在只会socket断开,但不会结束程序了
