### ISSUE TITLE
Linux运行报错，是系统版本的问题吗，需要更换系统吗

### ISSUE THREAD

**Issue by PICOF** [yuban10703/OPQ-SetuBot#25]
ERROR	可能是SendMsg返回为null
可能的原因：
1. 发送消息超过特定版本的长度限制，比如在x86_linux上发送超过215个汉字或645个ASCII
不想再装一遍系统啊

**Comment by PICOF** [comment]
我用的ubuntu64位

**Comment by yuban10703** [comment]
我这试了下好像没问题呀........
等两天吧 新的快写完了
