### ISSUE TITLE
botoy是什么

### ISSUE THREAD

**Issue by 1765766891** [yuban10703/OPQ-SetuBot#28]
C:\Users\17676\OPQ-SetuBot>
C:\Users\17676\OPQ-SetuBot>python bot.py
Traceback (most recent call last):
  File "C:\Users\17676\OPQ-SetuBot\bot.py", line 1, in <module>
    from botoy import Action, Botoy, GroupMsg, FriendMsg
ModuleNotFoundError: No module named 'botoy'

呜呜呜，不知道啥问题qwq

**Comment by yuban10703** [comment]
没装模块?

**Comment by yuban10703** [comment]
pip install -r requirements.txt

**Comment by 1765766891** [comment]
额，好吧，我傻了，我以为直接装了= =

**Comment by 1765766891** [comment]
还是一样的结局= =

**Comment by yuban10703** [comment]
...

**Comment by 1765766891** [comment]
好了，我刚刚更新了一下pp就好了，版本低了= =

**Comment by sayri23** [comment]
> pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
这个怎么解决，腾讯云的Ubuntu服务器，登录的root账户

**Comment by yuban10703** [comment]
> > pip install -r requirements.txt
> 
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
> 这个怎么解决，腾讯云的Ubuntu服务器，登录的root账户

没进到目录吧.....
