### ISSUE TITLE
疑似存在语法错误？？

### ISSUE THREAD

**Issue by AdminWhaleFall** [yuban10703/OPQ-SetuBot#29]
# 报错截图
![image](https://user-images.githubusercontent.com/63758849/108621420-75b53800-746d-11eb-878c-017a82d78e04.png)
# 系统信息：
- Linux raspberrypi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
- Python3.7版本
# 猜测：
> 可能是Python版本的问题叭

**Comment by yuban10703** [comment]
新语法py3.8开始支持的..
换py3.8+

**Comment by AdminWhaleFall** [comment]
# 找到问题原因了
> Python3.8中新增了赋值表达式“:=”操作符，简单来说就是把运算操作和赋值操作放在了一起，有点类似于“a+=b”这种表达方式，我想赋值表达式的出现应该是python追求简洁的传统理念所致。
# 后
你回`issues`好快哈 **（就喜欢这种）**，希望可以修改兼容一下Python3.X系列版本哈。

**Comment by AdminWhaleFall** [comment]
树莓派安装Python3.8坑好多，，，，

**Comment by yuban10703** [comment]
emm,现在的系统不都自带3.8了么 w(ﾟДﾟ)w

**Comment by AdminWhaleFall** [comment]
树莓派的源还是`Python3.7` 我自己已经改好了，谢谢啦！

**Comment by yuban10703** [comment]
嗯
