### ISSUE TITLE
加群报错

### ISSUE THREAD

**Issue by test-black** [yuban10703/OPQ-SetuBot#32]
![image](https://user-images.githubusercontent.com/28062894/108826024-c4dea280-75fe-11eb-85bd-198955f77a11.png)

复现操作：加群，执行“_cmd 开启群聊原图”

**Comment by yuban10703** [comment]
好像我哪里写错了,改好了..我测下....

**Comment by yuban10703** [comment]
改好了,试试有没有问题..

**Comment by test-black** [comment]
fixed
