### ISSUE TITLE
cmd命令问题

### ISSUE THREAD

**Issue by test-black** [yuban10703/OPQ-SetuBot#33]
![image](https://user-images.githubusercontent.com/28062894/108847611-df267980-761a-11eb-9e1f-200ffb2350eb.png)

复现：_cmd 修改群聊单次最大值 10

顺便问下命令类的默认值能写进config里面不，每次加群后都要单独设置略繁琐

**Comment by yuban10703** [comment]
wiki写错了..

**Comment by yuban10703** [comment]
_cmd 修改群聊单次最大值 int:10

**Comment by yuban10703** [comment]
配置文件在这里,修改可能比较麻烦....
![Uploading image.png…]()

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/108855384-ea31d780-7623-11eb-91c1-3293a877cf5f.png)

**Comment by test-black** [comment]
顺便问下tx对机器人发图次数的限制，有时候突然就发不出图了但api一切正常

**Comment by yuban10703** [comment]
可能是风控了，这得看tx心情。。

**Comment by test-black** [comment]
还有个问题，如果config.ini只开启了api_pixiv，"来张色图"该命令不会返回随机色图

**Comment by yuban10703** [comment]
Pixiv的api不能无tag搜索
