### ISSUE TITLE
请问搜图功能怎么用，还有为啥有的cmd命令用完会变成none

### ISSUE THREAD

**Issue by sayri23** [yuban10703/OPQ-SetuBot#34]

**Comment by sayri23** [comment]
_cmd 修改没找到的回复 你的xp好jb怪啊
下边列表里的这种，发完了就会变成none

**Comment by yuban10703** [comment]
_cmd 修改没找到的回复 str:你的xp好jb怪啊

**Comment by yuban10703** [comment]
wiki写错了..

**Comment by yuban10703** [comment]
![Y)54CTTJ7)6 UGLXLHGXL3P](https://user-images.githubusercontent.com/39484884/108856829-6b3d9e80-7625-11eb-8610-c220c98d3d6f.jpg)

**Comment by sayri23** [comment]
大佬，今天在新服务器上运行机器人时显示下边的错误，是Python版本问题吗？我已经安装了Python3.9
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from module import config, database
  File "/home/lighthouse/SETU/module/database.py", line 49
    if res := groupConfig.get(Q['GroupId'] == qqg):
            ^
SyntaxError: invalid syntax

**Comment by sayri23** [comment]
看样子好像是语法问题吧

**Comment by yuban10703** [comment]
python版本要>=3.8

**Comment by sayri23** [comment]
> python版本要>=3.8

安装的是3.9

**Comment by yuban10703** [comment]
没道理呀..你动过文件么?

**Comment by yuban10703** [comment]
你怎么运行的文件?

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/109131475-ce4a4500-778d-11eb-94c5-d440a681daf0.png)

**Comment by sayri23** [comment]
> 你怎么运行的文件?

Python3 bot.py啊

**Comment by yuban10703** [comment]
你输入python3 截图看看

**Comment by sayri23** [comment]
![~7_(%41JD6Q9J~@ HT4)JP](https://user-images.githubusercontent.com/62638560/109131889-313bdc00-778e-11eb-8b41-b3511cad9979.png)
安装了3.9，这里却显示3.6

**Comment by yuban10703** [comment]
....

**Comment by sayri23** [comment]
> ....
......
所以这个指向要怎么更改。。。

**Comment by yuban10703** [comment]
你输python3 按tab 应该有3.9吧

**Comment by sayri23** [comment]
有
lighthouse@VM-4-3-ubuntu:~$ python3
python3            python3.6-config   python3.6m-config  python3-config     python3m-config
python3.6          python3.6m         python3.9          python3m

**Comment by yuban10703** [comment]
不是有3.9么,把pip改到3.9装包,用3.9运行就好了

**Comment by sayri23** [comment]
> 不是有3.9么,把pip改到3.9装包,用3.9运行就好了

ok，谢谢
