### ISSUE TITLE
群聊没反应怎么办

### ISSUE THREAD

**Issue by 159764** [yuban10703/OPQ-SetuBot#35]
就是我群聊发什么他都没反应，群聊还正常。然后使用指令都没反应，除了私聊色图。然后问题之前昨天上午我一次性给他塞了好几个指令然后就这样了

**Comment by 159764** [comment]
2021-02-24 13:35:27 SUCCESS	更新群信息成功~
ℹ️ 2021-02-24 13:36:08 INFO	从本地数据库获取到0张关于[]的setu  实际发送0张
ℹ️ 2021-02-24 13:36:09 INFO	从yubanのapi获取到1张关于[]的setu  实际发送1张
❌ 2021-02-24 13:36:09 ERROR	返回为null
ℹ️ 2021-02-24 13:36:09 INFO	从yubanのapi获取到1张关于[]的setu  实际发送1张
ℹ️ 2021-02-24 13:36:33 INFO	从本地数据库获取到0张关于[]的setu  实际发送0张
❌ 2021-02-24 13:36:44 ERROR	返回为null
ℹ️ 2021-02-24 13:36:44 INFO	从yubanのapi获取到1张关于[]的setu  实际发送1张
ℹ️ 2021-02-24 13:38:38 INFO	从本地数据库获取到0张关于[]的setu  实际发送0张
ℹ️ 2021-02-24 13:38:40 INFO	从yubanのapi获取到1张关于[]的setu  实际发送1张
❌ 2021-02-24 13:39:01 ERROR	返回为null
ℹ️ 2021-02-24 13:39:01 INFO	从yubanのapi获取到1张关于[]的setu  实际发送1张
ℹ️ 2021-02-24 13:43:29 INFO	从本地数据库获取到0张关于[]的setu  实际发送0张
ℹ️ 2021-02-24 13:43:40 INFO	从yubanのapi获取到1张关于[]的setu  实际发送1张
ℹ️ 2021-02-24 13:54:24 INFO	群:551778930第一次调用
ℹ️ 2021-02-24 13:54:24 INFO	从本地数据库获取到0张关于[]的setu  实际发送0张
❌ 2021-02-24 13:54:37 ERROR	返回为null
ℹ️ 2021-02-24 13:54:37 INFO	从yubanのapi获取到1张关于[]的setu  实际发送1张

**Comment by yuban10703** [comment]
风控了，挂机几天说不定就好了

**Comment by 159764** [comment]
哦，了解
