### ISSUE TITLE
只设置api_pixiv=1的问题

### ISSUE THREAD

**Issue by test-black** [yuban10703/OPQ-SetuBot#36]
![image](https://user-images.githubusercontent.com/28062894/109017935-9b9f3e80-76f2-11eb-9665-ad3c6fd5ff0a.png)

复现：
![image](https://user-images.githubusercontent.com/28062894/109018024-b1acff00-76f2-11eb-91c9-5970184719b5.png)

来2张xx色图

**Comment by test-black** [comment]
请问下yuban这个api的调用限制，测试的时候估计触发了限制阈值，返回null但过一会又好了。

**Comment by test-black** [comment]
另一个cmd命令问题

**Comment by test-black** [comment]
另一个cmd命令：_cmd 修改群聊单次最大值 int:3
先修改为10再修改为3报错

![image](https://user-images.githubusercontent.com/28062894/109023847-1a4aaa80-76f8-11eb-9a65-ace4750b1ec2.png)

**Comment by HeiLAAS** [comment]
> 请问下yuban这个api的调用限制，测试的时候估计触发了限制阈值，返回null但过一会又好了。

这个重启下插件没准好了

**Comment by yuban10703** [comment]
> 另一个cmd命令：_cmd 修改群聊单次最大值 int:3
> 先修改为10再修改为3报错
> 
> ![image](https://user-images.githubusercontent.com/28062894/109023847-1a4aaa80-76f8-11eb-9a65-ace4750b1ec2.png)

没问题啊,你手动改数据库了?

**Comment by yuban10703** [comment]
> 请问下yuban这个api的调用限制，测试的时候估计触发了限制阈值，返回null但过一会又好了。

这个api没限制
