### ISSUE TITLE
当前版本为: 0.0.19, 已有最新版本: 0.0.22

### ISSUE THREAD

**Issue by test-black** [yuban10703/OPQ-SetuBot#37]
![image](https://user-images.githubusercontent.com/28062894/111742528-4c989380-88c3-11eb-8674-72ca6d8351a9.png)

**Comment by yuban10703** [comment]
这是botoy的更新
pip3 install botoy -i https://pypi.org/simple --upgrade

**Comment by test-black** [comment]
已解决
