### ISSUE TITLE
 WARNING   刷新Pixiv_token出错

### ISSUE THREAD

**Issue by test-black** [yuban10703/OPQ-SetuBot#38]
从selenium脚本获取到refreshtoken后报错，国外机器
![image](https://user-images.githubusercontent.com/28062894/111743765-24119900-88c5-11eb-8bfa-1f5011faca80.png)

**Comment by yuban10703** [comment]
不应该呀，看看你格式

**Comment by test-black** [comment]
![Uploading image.png…]()

**Comment by yuban10703** [comment]
你机子确定可以访问p站么。。

**Comment by test-black** [comment]
![image](https://user-images.githubusercontent.com/28062894/111744776-b5353f80-88c6-11eb-805e-2e125e71e05a.png)

**Comment by test-black** [comment]
是不是刷新的地址改了

**Comment by yuban10703** [comment]
我试试

**Comment by yuban10703** [comment]
![IMG20210319152857](https://user-images.githubusercontent.com/39484884/111745667-e4987c00-88c7-11eb-8566-796c424fab52.jpg)


试了一下，好像没问题呀。。。

**Comment by test-black** [comment]
git reset --hard 之后再替换.PixivToken文件又好了，迷。。。
