### ISSUE TITLE
功能建议2（完善）

### ISSUE THREAD

**Issue by githubdl** [yuban10703/OPQ-SetuBot#6]
大佬，可以增加一个到了刷新时间，就发一条信息，“冷却完毕”，这样的功能吗？

**Comment by yuban10703** [comment]
OK

**Comment by yuban10703** [comment]
不太好弄,过几天再整..........

**Comment by githubdl** [comment]
> 不太好弄,过几天再整..........

好的
（我好像发现发送图片的函数不可以艾特人回复，但是发送文字的函数可以艾特人回复，不知道是不是原作者开发的bug）

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/86002582-1c624980-ba43-11ea-81b7-68af1e449c6a.png)

**Comment by yuban10703** [comment]
图片@要这么用

**Comment by githubdl** [comment]
> 图片@要这么用

多谢大佬指点，看来是我太菜了，也就是说是在content里面加上[ATUSER(QQ号)]咯，那QQ号可以用FromQQ这个变量来代替吗？（就是可以达到艾特触发关键词的那个人）

**Comment by yuban10703** [comment]
应该可以⑧,emmm

**Comment by githubdl** [comment]
> 应该可以⑧,emmm

我试了好多变量都没用，请问大佬知道在[ATUSER()]这个()里面填写什么可以艾特触发关键词的那个人不？

**Comment by yuban10703** [comment]
应该是fromQQ吧

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/86012359-74537d00-ba50-11ea-9f80-d121b3f9fd3e.png)

**Comment by githubdl** [comment]
> 应该是fromQQ吧

我在()里填写FromQQ，没有啥效果，然后如果是填写成'FromQQ'，就无法运行

**Comment by githubdl** [comment]
你发的这个图，我加载不出来呢，是我这边的问题吗？

**Comment by yuban10703** [comment]
科学上网试试..

**Comment by yuban10703** [comment]
> > 应该是fromQQ吧
> 
> 我在()里填写FromQQ，没有啥效果，然后如果是填写成'FromQQ'，就无法运行

看看代码....?

**Comment by githubdl** [comment]
> > > 应该是fromQQ吧
> > 
> > 
> > 我在()里填写FromQQ，没有啥效果，然后如果是填写成'FromQQ'，就无法运行
> 
> 看看代码....?

`        msg = '不理你了\n[PICFLAG][ATUSER(FromQQ)]'`
这个代码可以运行，但是不会艾特人
`        msg = '不理你了\n[PICFLAG][ATUSER('FromQQ')]'`
这个代码无法运行

**Comment by yuban10703** [comment]
啊???...

**Comment by githubdl** [comment]
> 啊???...

是要完整的吗？我再弄一下
`    if a.At_Content == '爬':
        with open('./picture/不理你了.png', 'rb') as f:
            content = f.read()
        b64 = base64.b64encode(content).decode()
        msg = '不理你了\n[PICFLAG][ATUSER('FromQQ')]'
        # send_text(a, msg)
        send_pic(mess = a, msg = msg, atuser = a.FromQQ, picbase64= b64)
        return `

**Comment by githubdl** [comment]
> 啊???...

```
    if a.At_Content == '爬':
        with open('./picture/不理你了.png', 'rb') as f:
            content = f.read()
        b64 = base64.b64encode(content).decode()
        msg = '不理你了\n[PICFLAG][ATUSER('mess.FromQQ')]'
        # send_text(a, msg)
        send_pic(mess = a, msg = msg, atuser = a.FromQQ, picbase64= b64)
        return 
```

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/86014436-e927b680-ba52-11ea-8fc3-b569b8da627f.png)

你这代码都是错的吧.......?

**Comment by githubdl** [comment]
> ![image](https://user-images.githubusercontent.com/39484884/86014436-e927b680-ba52-11ea-8fc3-b569b8da627f.png)
> 
> 你这代码都是错的吧.......?

不是呀，在没有加[ATUSER('mess.FromQQ')]这个之前，代码都是可以正常运行的。
主要是想实现艾特触发关键词的人的功能，一直找不到正确方法

**Comment by yuban10703** [comment]
用format带到msg里

**Comment by githubdl** [comment]
> 用format带到msg里

多谢大佬指点，已经实现了功能
