### ISSUE TITLE
求助帖 status_code=500

### ISSUE THREAD

**Issue by camenkc** [yuban10703/OPQ-SetuBot#7]
摸了一天也无解，早上来发个iss求助QwQ

![UUS_SS(6OWT$Q{WMR(O58UX](https://user-images.githubusercontent.com/25873495/86071569-2ec79c00-bab2-11ea-8120-b86670fd9084.png)

尝试把setu库clone下来：

![Y3O@TYQ99{_}RA5LUTM2TWN](https://user-images.githubusercontent.com/25873495/86071632-5585d280-bab2-11ea-9493-6ec91b927679.png)

注销掉try-except报错如下：

![7%52S6LVJFH7_RRFIIN@`(P](https://user-images.githubusercontent.com/25873495/86072044-481d1800-bab3-11ea-8fcb-13c22142e4f0.png)

有解决方案当然非常感激，告诉原因也算学到知识，也很感谢哦

**Comment by yuban10703** [comment]
看看config

**Comment by camenkc** [comment]
setu姬的config
![2S81X@3E}R74HV~`V90U%F3](https://user-images.githubusercontent.com/25873495/86082808-419a9a80-bacb-11ea-9b92-863e17499ac6.png)

IOTQQ的config
![MJ%(77ZBJ@UT9KG{)4CXOLC](https://user-images.githubusercontent.com/25873495/86082828-49f2d580-bacb-11ea-9cbc-349cafc20ee2.png)

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/86082982-a48c3180-bacb-11ea-9f8c-f36e565a14e3.png)

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/86083231-38f69400-bacc-11ea-8360-5f452fef3253.png)
把斜杠去掉试试

**Comment by camenkc** [comment]
成功了 谢谢谢谢 三连献上
