### ISSUE TITLE
【求助】卑微菜鸡查不出错。。。。

### ISSUE THREAD

**Issue by freechar** [yuban10703/OPQ-SetuBot#9]
![QQ截图20200730133805](https://user-images.githubusercontent.com/39230802/88884794-eabee700-d269-11ea-9fd1-b348237b6392.png)
![QQ截图20200730133837](https://user-images.githubusercontent.com/39230802/88884864-088c4c00-d26a-11ea-9daf-5bb076179007.png)

**Comment by yuban10703** [comment]
怎么了?........

**Comment by freechar** [comment]
没法发出消息，，，不知道为什么，但是能检测到要他发图的请求

**Comment by yuban10703** [comment]
> 没法发出消息，，，不知道为什么，但是能检测到要他发图的请求

私聊呢?

**Comment by freechar** [comment]
同样发不出来，很迷惑

**Comment by yuban10703** [comment]
> 同样发不出来，很迷惑

看看log

**Comment by freechar** [comment]
![image](https://user-images.githubusercontent.com/39230802/89016360-2da4bb80-d34b-11ea-8167-6ea507060dc2.png)

**Comment by yuban10703** [comment]
不是这个log.......
插件运行时候的输出

**Comment by freechar** [comment]
哦哦哦

**Comment by freechar** [comment]
莫名奇妙好了，，，，我什么都没修改的说

**Comment by yuban10703** [comment]
..

**Comment by freechar** [comment]
很迷惑

**Comment by freechar** [comment]
还是在这里感谢了
